### ISSUE TITLE
No button for downloading the video

### ISSUE THREAD

**Issue by PigeonMatt** [crustySenpai/yt1s-Youtube-Downloader-Userscript#1]
![obraz_2022-08-15_225335392](https://user-images.githubusercontent.com/105587275/184716476-05826010-4faa-4cb1-ac62-235dded20ebc.png)

**Comment by crustySenpai** [comment]
Hmm weird should look like this, try to use a different userscript manager or re-add the script

![Screenshot_1](https://user-images.githubusercontent.com/83429736/185579866-aa11590d-c86f-40dc-a8e0-f0a58057252e.png)
